name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Or your desired Node.js version
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm test

  release:
    runs-on: ubuntu-latest
    needs: test # This job depends on the 'test' job
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Or your desired Node.js version
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Archive release packet
        uses: actions/upload-artifact@v3
        with:
          name: release-packet
          path: dist/
